import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { Archive, MailOpen, Star, Trash2 } from 'lucide-react';
import Layout from '../components/Layout';
import ProtectedRoute from '../components/ProtectedRoute';
import api from '../services/api';

function Inbox() {
  const router = useRouter(); const [result, setResult] = useState(null); const [error, setError] = useState('');
  const query = typeof router.query.q === 'string' ? router.query.q : '';
  useEffect(() => { if (!router.isReady) return; setResult(null); setError(''); const url = query ? `/emails/search?q=${encodeURIComponent(query)}` : '/emails'; api.get(url).then(({ data }) => setResult(data)).catch((requestError) => setError(requestError.response?.data?.message || 'Could not load mail.')); }, [router.isReady, query]);
  async function action(event, id, actionName) { event.preventDefault(); event.stopPropagation(); try { await api[actionName === 'delete' ? 'delete' : 'post'](`/emails/${id}${actionName === 'delete' ? '' : `/${actionName}`}`); setResult((current) => ({ ...current, emails: current.emails.filter((email) => actionName === 'delete' || actionName === 'archive' ? email.id !== id : true).map((email) => actionName === 'star' && email.id === id ? { ...email, isStarred: true } : email) })); } catch (requestError) { setError(requestError.response?.data?.message || 'Email action failed.'); } }
  return <Layout><div className="flex items-baseline justify-between gap-3"><div><h1 className="text-2xl font-bold">Inbox</h1>{query && <p className="mt-1 text-sm text-slate-600 dark:text-slate-400">Search results for “{query}”</p>}</div><Link href="/integrations" className="text-sm font-medium text-blue-700 dark:text-blue-400">Gmail connection</Link></div>{error && <p className="mt-5 rounded-md bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/50 dark:text-red-300">{error}</p>}{!result && !error && <p className="mt-8 text-slate-600 dark:text-slate-400">Loading messages…</p>}{result && <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-800">{result.emails.length === 0 ? <p className="p-6 text-sm text-slate-600 dark:text-slate-400">No messages found.</p> : result.emails.map((email) => <Link key={email.id} href={`/email/${email.id}`} className={`flex items-start gap-3 border-b border-slate-100 p-4 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-700/50 ${email.isRead ? 'text-slate-600 dark:text-slate-400' : 'font-semibold text-slate-900 dark:text-slate-100'}`}><button onClick={(event) => action(event, email.id, email.isStarred ? 'unstar' : 'star')} aria-label="Toggle star" className="mt-0.5 text-amber-500"><Star size={18} fill={email.isStarred ? 'currentColor' : 'none'} /></button><div className="min-w-0 flex-1"><div className="flex justify-between gap-4"><span className="truncate">{email.sender}</span><time className="shrink-0 text-xs font-normal">{email.timestamp ? new Date(email.timestamp).toLocaleString() : ''}</time></div><p className="truncate text-sm"><span>{email.subject}</span><span className="font-normal text-slate-500 dark:text-slate-400"> — {email.snippet}</span></p></div><div className="hidden gap-2 sm:flex"><button onClick={(event) => action(event, email.id, 'read')} aria-label="Mark as read"><MailOpen size={17} /></button><button onClick={(event) => action(event, email.id, 'archive')} aria-label="Archive"><Archive size={17} /></button><button onClick={(event) => action(event, email.id, 'delete')} aria-label="Delete"><Trash2 size={17} /></button></div></Link>)}</section>}</Layout>;
}
export default function Page() { return <ProtectedRoute><Inbox /></ProtectedRoute>; }
