import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { Archive, Star, Trash2 } from 'lucide-react';
import Layout from '../../components/Layout';
import ProtectedRoute from '../../components/ProtectedRoute';
import ReplyComposer from '../../components/ReplyComposer';
import api from '../../services/api';

function EmailDetail() {
  const router = useRouter(); const [data, setData] = useState(null); const [error, setError] = useState(''); const [reloadKey, setReloadKey] = useState(0);
  useEffect(() => { if (!router.isReady) return; api.get(`/emails/${router.query.id}`).then(({ data: response }) => setData(response)).catch((requestError) => setError(requestError.response?.data?.message || 'Could not load this email.')); }, [router.isReady, router.query.id, reloadKey]);
  async function action(name) { try { await api[name === 'delete' ? 'delete' : 'post'](`/emails/${router.query.id}${name === 'delete' ? '' : `/${name}`}`); router.push('/inbox'); } catch (requestError) { setError(requestError.response?.data?.message || 'Email action failed.'); } }
  return <Layout><Link href="/inbox" className="text-sm font-medium text-blue-700 dark:text-blue-400">← Inbox</Link>{error && <p className="mt-5 text-red-600 dark:text-red-400">{error}</p>}{!data && !error && <p className="mt-6 text-slate-600 dark:text-slate-400">Loading email…</p>}{data && <><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{data.email.subject}</h1><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">{data.email.sender} · {data.email.timestamp && new Date(data.email.timestamp).toLocaleString()}</p></div><div className="flex gap-2"><button onClick={() => action('star')} className="rounded border border-slate-200 p-2 dark:border-slate-700" aria-label="Star"><Star size={18} /></button><button onClick={() => action('archive')} className="rounded border border-slate-200 p-2 dark:border-slate-700" aria-label="Archive"><Archive size={18} /></button><button onClick={() => action('delete')} className="rounded border border-slate-200 p-2 dark:border-slate-700" aria-label="Delete"><Trash2 size={18} /></button></div></div><section className="mt-6 rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-800"><div className="whitespace-pre-wrap break-words text-sm leading-7">{data.email.body || data.email.snippet}</div>{data.email.attachments.length > 0 && <p className="mt-6 text-sm text-slate-500 dark:text-slate-400">Attachments: {data.email.attachments.map((item) => item.filename).join(', ')}</p>}</section>{data.thread.length > 1 && <section className="mt-6"><h2 className="font-semibold">Conversation</h2><div className="mt-3 space-y-3">{data.thread.map((message) => <article key={message.id} className="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><p className="text-sm font-medium">{message.sender}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700 dark:text-slate-300">{message.body || message.snippet}</p></article>)}</div></section>}<ReplyComposer emailId={router.query.id} onReplySuccess={() => setReloadKey((key) => key + 1)} /></>}</Layout>;
}
export default function Page() { return <ProtectedRoute><EmailDetail /></ProtectedRoute>; }
