import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { Archive, Bot, Star, Trash2, X } from 'lucide-react';
import Layout from '../../components/Layout';
import ProtectedRoute from '../../components/ProtectedRoute';
import api from '../../services/api';

function AIPanel({ emailId }) {
  const [error, setError] = useState(''); const [loading, setLoading] = useState('');
  const [summary, setSummary] = useState(''); const [explanation, setExplanation] = useState('');
  const [category, setCategory] = useState(''); const [reply, setReply] = useState('');
  async function run(action) {
    setError(''); setLoading(action);
    try { const { data } = await api.post(`/ai/${action}/${emailId}`); if (action === 'summarize') setSummary(data.summary); if (action === 'explain') setExplanation(data.explanation); if (action === 'classify') setCategory(data.category); if (action === 'reply') setReply(data.reply); }
    catch (requestError) { setError(requestError.response?.data?.message || 'AI generation failed. Please try again.'); }
    finally { setLoading(''); }
  }
  const labels = { summarize: 'Summarize', explain: 'Explain this email', classify: 'Classify', reply: reply ? 'Regenerate reply' : 'Generate reply' };
  return <section className="mt-6 rounded-xl border border-blue-100 bg-blue-50/50 p-5"><div className="flex items-center gap-2"><Bot size={18} className="text-blue-700" /><h2 className="font-semibold">AI assistance</h2></div><p className="mt-1 text-sm text-slate-600">AI-generated content is for review and may be inaccurate.</p><div className="mt-4 flex flex-wrap gap-2">{Object.keys(labels).map((action) => <button key={action} onClick={() => run(action)} disabled={Boolean(loading)} className="rounded-md border border-blue-200 bg-white px-3 py-2 text-sm font-medium text-blue-800 disabled:opacity-60">{loading === action ? 'Generating…' : labels[action]}</button>)}</div>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}{category && <p className="mt-4 rounded-md bg-white p-3 text-sm"><span className="font-medium">AI classification:</span> {category}</p>}{summary && <article className="mt-4 rounded-md bg-white p-4"><h3 className="text-sm font-semibold text-blue-900">AI summary</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{summary}</p></article>}{explanation && <article className="mt-4 rounded-md bg-white p-4"><h3 className="text-sm font-semibold text-blue-900">AI explanation</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{explanation}</p></article>}{reply && <article className="mt-4 rounded-md bg-white p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-blue-900">AI-generated reply — edit before sending</h3><button onClick={() => setReply('')} className="rounded p-1 text-slate-500 hover:bg-slate-100" aria-label="Cancel generated reply"><X size={17} /></button></div><textarea value={reply} onChange={(event) => setReply(event.target.value)} rows={8} className="mt-3 w-full rounded-md border border-slate-300 p-3 text-sm leading-6" aria-label="Editable AI-generated reply" /><p className="mt-2 text-xs text-slate-500">Sending replies is intentionally not available until Phase 5.</p></article>}</section>;
}

function EmailDetail() {
  const router = useRouter(); const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { if (!router.isReady) return; api.get(`/emails/${router.query.id}`).then(({ data: response }) => setData(response)).catch((requestError) => setError(requestError.response?.data?.message || 'Could not load this email.')); }, [router.isReady, router.query.id]);
  async function action(name) { try { await api[name === 'delete' ? 'delete' : 'post'](`/emails/${router.query.id}${name === 'delete' ? '' : `/${name}`}`); router.push('/inbox'); } catch (requestError) { setError(requestError.response?.data?.message || 'Email action failed.'); } }
  return <Layout><Link href="/inbox" className="text-sm font-medium text-blue-700">← Inbox</Link>{error && <p className="mt-5 text-red-600">{error}</p>}{!data && !error && <p className="mt-6 text-slate-600">Loading email…</p>}{data && <><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{data.email.subject}</h1><p className="mt-1 text-sm text-slate-600">{data.email.sender} · {data.email.timestamp && new Date(data.email.timestamp).toLocaleString()}</p></div><div className="flex gap-2"><button onClick={() => action('star')} className="rounded border p-2" aria-label="Star"><Star size={18} /></button><button onClick={() => action('archive')} className="rounded border p-2" aria-label="Archive"><Archive size={18} /></button><button onClick={() => action('delete')} className="rounded border p-2" aria-label="Delete"><Trash2 size={18} /></button></div></div><section className="mt-6 rounded-xl border border-slate-200 bg-white p-6"><div className="whitespace-pre-wrap break-words text-sm leading-7">{data.email.body || data.email.snippet}</div>{data.email.attachments.length > 0 && <p className="mt-6 text-sm text-slate-500">Attachments: {data.email.attachments.map((item) => item.filename).join(', ')}</p>}</section>{data.thread.length > 1 && <section className="mt-6"><h2 className="font-semibold">Conversation</h2><div className="mt-3 space-y-3">{data.thread.map((message) => <article key={message.id} className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-sm font-medium">{message.sender}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{message.body || message.snippet}</p></article>)}</div></section>}</>}</Layout>;
}
export default function Page() { return <ProtectedRoute><EmailDetail /></ProtectedRoute>; }
